config/routes.rb
Rails.application.routes.draw do
  resources :units
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#index'
  get 'homepage', to: 'pages#homepage', as: 'homepage'
  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'user_details', to: 'pages#user_details', as: 'user_details'
  get 'calendar_legend', to:'pages#calendar_legend', as: 'calendar_legend'
  get 'how_to', to:'pages#how_to', as:'how_to'

  get '/redirect', to: 'events#redirect', as: 'redirect'
  get '/callback', to: 'events#callback', as: 'callback'
  get '/calendar', to: 'events#calendar', as: 'calendar'
  get '/events/:calendar_id', to: 'events#events', as: 'events', calendar_id: /[^\/]+/


  resources :bookings
  get 'booking_table', to:'bookings#booking_table', as:'booking_table'
  get 'request_message', to:'bookings#request_message', as:'request_message'
  post 'create_booking', to: 'bookings#create', as:'create_booking'
  put 'approve_booking/:id', to:'bookings#approve', as:'approve_booking'
  put 'deny_booking/:id', to:'bookings#deny', as:'deny_booking'
  put 'cancel_booking/:id', to:'bookings#cancel', as:'cancel_booking'
  post '/events/:calendar_id', to: 'bookings#new_event', as: 'new_event', calendar_id: /[^\/]+/
  # post 'destroy_bookings_and_events', to:'bookings#destroy_bookings_and_events', as: 'destroy_bookings_and_events'

  post 'delete_calendar', to:'units#delete_calendar', as:'delete_calendar'

  post 'twilio/sms'


  get 'bio', to:'users#bio', as:'bio'
  get 'user_table', to: 'users#index', as: 'user_table'


  #Devise routes for logging in, registrations
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy', as:'get_destroy_user_session'
  end




end

app/views/pages/dashboard/_dashboard.html.erb
<%= stylesheet_link_tag "legend" %>


<% if host %>
  <div class='row'><h2 id='dashboard-title'>Host Dashboard</h2></div>
<% elsif cleaner %>
  <div class='row'><h2 id='dashboard-title'>Cleaner Dashboard</h2></div>
<% end %>

    <div class="row" id="tabs">
      <div class="col-sm-3"> <%= link_to 'Listings', units_path, :id=>'listings' %> </div>
    <% if host %>
      <div class="col-sm-2"> <%= link_to 'Cleaners', user_table_path, :id=>'users' %> </div>
    <% elsif cleaner %>
      <div class="col-sm-2"> <%= link_to 'Hosts', user_table_path, :id=>'users' %> </div>
    <% end %>
      <div class="col-sm-2"> <%= link_to 'Earnings', dashboard_path, :id=>'earnings' %> </div>
      <div class="col-sm-2"> <%= link_to 'History', dashboard_path, :id=>'history' %> </div>
      <div class="col-sm-3"> <%= link_to 'How To', how_to_path, :id=>'faq' %> </div>
    </div>



    <div class="row" id="row1">
      <%= render upcoming_bookings_card_partial_path %>
      <%= render earnings_card_partial_path %>
      <%= render pending_bookings_card_partial_path %>
      <%= render approved_bookings_card_partial_path %>
    </div>

    <div class="row">
    <div id='calendar-container'>
      <%= render 'pages/dashboard/cards/legend' %>
      <%= render '/events/calendar' %>
    </div>
    </div>