config/routes.rb
Rails.application.routes.draw do
  resources :units
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#index'
  get 'homepage', to: 'pages#homepage', as: 'homepage'
  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'user_details', to: 'pages#user_details', as: 'user_details'
  get 'calendar_legend', to:'pages#calendar_legend', as: 'calendar_legend'
  get 'how_to', to:'pages#how_to', as:'how_to'

  get '/redirect', to: 'events#redirect', as: 'redirect'
  get '/callback', to: 'events#callback', as: 'callback'
  get '/calendar', to: 'events#calendar', as: 'calendar'
  get '/events/:calendar_id', to: 'events#events', as: 'events', calendar_id: /[^\/]+/


  resources :bookings
  get 'booking_table', to:'bookings#booking_table', as:'booking_table'
  get 'request_message', to:'bookings#request_message', as:'request_message'
  post 'create_booking', to: 'bookings#create', as:'create_booking'
  put 'approve_booking/:id', to:'bookings#approve', as:'approve_booking'
  put 'deny_booking/:id', to:'bookings#deny', as:'deny_booking'
  put 'cancel_booking/:id', to:'bookings#cancel', as:'cancel_booking'
  post '/events/:calendar_id', to: 'bookings#new_event', as: 'new_event', calendar_id: /[^\/]+/
  # post 'destroy_bookings_and_events', to:'bookings#destroy_bookings_and_events', as: 'destroy_bookings_and_events'

  post 'delete_calendar', to:'units#delete_calendar', as:'delete_calendar'

  post 'twilio/sms'


  get 'bio', to:'users#bio', as:'bio'
  get 'user_table', to: 'users#index', as: 'user_table'


  #Devise routes for logging in, registrations
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy', as:'get_destroy_user_session'
  end




end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :host_bookings, :class_name => 'Booking', :foreign_key => 'host_id'
  has_many :cleaner_bookings, :class_name => 'Booking', :foreign_key => 'cleaner_id'
  has_many :units, :class_name => 'Unit', :foreign_key => 'owner_id'

  TYPES=[
    ['host','Host'],
    ['cleaner','Cleaner']
  ]


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    if current_user.user_type == 'host'
      @users = User.where(:user_type => 'cleaner').paginate(:page => params[:page], :per_page => 5)
    else
      @users = User.where(:user_type=>'host').paginate(:page => params[:page], :per_page => 5)
    end
  end

  def show
    @user = current_user
  end

  def bio
    @user = User.find params[:test]
  end

  def post

  end

end

app/helpers/users_helper.rb
module UsersHelper

  def host
    current_user.user_type == 'host'
  end

  def cleaner
    current_user.user_type == 'cleaner'
  end

end

app/views/users/user_table/_user_table.html.erb
<div style='text-align:center'>
<%= link_to 'Back', dashboard_path %></div>

<% if host %>
  <h1 style='text-align:center'> Here are a list of Cleaners </h1>
<% elsif cleaner %>
  <h1 style='text-align:center'> Here are a list of Hosts </h1>
<% end %>

  <div class="col-sm-6" id="calendar-container">
    <table class = "table">
      <thead>
      <tr>
        <th scope='col'>id</th>
        <th scope='col'>name</th>
        <th scope='col'>email</th>
        <th scope='col'>Request</th>
      </tr>

      <tbody>
        <% count = 1 %>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <% if host %>
              <td><%= link_to user.name, new_booking_path(cleaner_id: user.id, host_id: current_user.id)  %></td>
              <td><%= user.email %></td>
              <td><%= link_to 'Book Now!', new_booking_path(cleaner_id: user.id, host_id: current_user.id), class: 'btn btn-primary btn-sm' %></td>
            <% elsif cleaner %>
              <td><%= link_to user.name, new_booking_path(cleaner_id: current_user.id, host_id: user.id)  %></td>
              <td><%= user.email %></td>
              <td><%= link_to 'Book Now!', new_booking_path(cleaner_id: current_user.id, host_id: user.id), class: 'btn btn-primary btn-sm' %></td>
            <% end %>

            <% count += 1 %>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @users %>

  </div>