config/routes.rb
Rails.application.routes.draw do
  resources :units
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#index'
  get 'homepage', to: 'pages#homepage', as: 'homepage'
  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'user_details', to: 'pages#user_details', as: 'user_details'
  get 'calendar_legend', to:'pages#calendar_legend', as: 'calendar_legend'
  get 'how_to', to:'pages#how_to', as:'how_to'

  get '/redirect', to: 'events#redirect', as: 'redirect'
  get '/callback', to: 'events#callback', as: 'callback'
  get '/calendar', to: 'events#calendar', as: 'calendar'
  get '/events/:calendar_id', to: 'events#events', as: 'events', calendar_id: /[^\/]+/


  resources :bookings
  get 'booking_table', to:'bookings#booking_table', as:'booking_table'
  get 'request_message', to:'bookings#request_message', as:'request_message'
  post 'create_booking', to: 'bookings#create', as:'create_booking'
  put 'approve_booking/:id', to:'bookings#approve', as:'approve_booking'
  put 'deny_booking/:id', to:'bookings#deny', as:'deny_booking'
  put 'cancel_booking/:id', to:'bookings#cancel', as:'cancel_booking'
  post '/events/:calendar_id', to: 'bookings#new_event', as: 'new_event', calendar_id: /[^\/]+/
  # post 'destroy_bookings_and_events', to:'bookings#destroy_bookings_and_events', as: 'destroy_bookings_and_events'

  post 'delete_calendar', to:'units#delete_calendar', as:'delete_calendar'

  post 'twilio/sms'


  get 'bio', to:'users#bio', as:'bio'
  get 'user_table', to: 'users#index', as: 'user_table'


  #Devise routes for logging in, registrations
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy', as:'get_destroy_user_session'
  end




end

app/models/unit.rb
class Unit < ApplicationRecord
    belongs_to :owner, :class_name => 'User'

    has_many :bookings, :class_name => 'Booking', :foreign_key => 'unit_id', dependent: :delete_all

end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /units/1
  # GET /units/1.json
  def show
    client = Signet::OAuth2::Client.new(client_options)
    client.update!(session[:authorization])
    service = Google::Apis::CalendarV3::CalendarService.new
    service.authorization = client
    # @calendar = service.get_calendar(:primary)
    @calendar_list = service.list_calendar_lists
    @calendar = service.get_calendar(:primary).id

    @list = @calendar_list.items.map do |c|
      [c.summary_override, c.id]
    end

    # @unit_cleanings = Booking.select do |booking|
    #   booking.unit.calendar_id == params[:calendar_id]
    # end
    # render json: @bookings

  rescue Google::Apis::AuthorizationError
    response = client.refresh!
    session[:authorization] = session[:authorization].merge(response)
    retry
  end

  # GET /units/new
  def new
    @unit = Unit.new
    return show
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(
      name: unit_params[:name],
      calendar_id: unit_params[:calendar_id],
      owner_id: unit_params[:owner_id],
      address: unit_params[:address],
      city: unit_params[:city],
      state: unit_params[:state],
      zip_code: unit_params[:zip_code]
    )

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    delete_calendar

    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delete_calendar
    @unit = Unit.find(params[:id])

    client = Signet::OAuth2::Client.new(client_options)
    client.update!(session[:authorization])
    service = Google::Apis::CalendarV3::CalendarService.new
    service.authorization = client
    # client = service.get_calendar(@unit.calendar_id)
    # client = service.list_calendar_lists
    service.delete_calendar_list(@unit.calendar_id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name, :calendar_id, :address, :city, :state,
         :zip_code, :owner_id, :utf8, :authenticity_token, :commit)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= form_with(model: unit, local: true) do |form| %>
  <% if unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editing Unit</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<script>

$(document).ready(function(){
  $('[data-toggle="tooltip"]').tooltip();
});

</script>

<div style='text-align:center'>
<%= link_to 'Back', dashboard_path %></div>

<div class="centered-table">

<h1 style='text-align:center; margin-top:3rem;'>Units</h1>


  <table class='table'>
    <thead>
      <tr>
        <th scope='col'>Unit Name</th>
        <th scope='col'>Unit Owner</th>
        <th scope='col'>Location</th>
        <th scope='col'>Edit</th>
        <th scope='col'>Remove</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% if current_user.user_type == 'cleaner' %>
      <% @units.each do |unit| %>
        <tr>
          <td><%= link_to "#{unit.name}", unit %></td>
          <td><%= link_to "#{unit.owner.name}", unit %></td>
          <td><%= link_to "#{unit.city},#{unit.state}", unit %></td>
        </tr>
      <% end %>
      <% elsif current_user.user_type == 'host' %>
      <% @units.where(owner_id:current_user.id).each do |unit| %>
        <tr>
          <td><%= link_to "#{unit.name}", unit %></td>
          <td><%= link_to "#{unit.owner.name}", unit %></td>
          <td><%= link_to "#{unit.city},#{unit.state}", unit %></td>
          <% if current_user.id == unit.owner.id %>
            <td><%= button_to 'Edit', edit_unit_path(unit), class: 'btn btn-primary btn-sm', method: :get %></td>
            <td><%= button_to 'Destroy', unit, class: 'btn btn-danger btn-sm', method: :delete, data: { confirm: 'Are you sure? This will remove this unit and un-sync its reservations from your main calendar' } %></td>
          <% end %>
        </tr>
      <% end %>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @units %>





  <br>
  <% if current_user.user_type == 'host' %>
  <%= link_to 'New Unit', new_unit_path %>
  <% end %>
</div>

app/views/units/new.html.erb
<div class = 'container' style='width:70rem;'>
  <h1 style='text-align:center'>New Unit</h1>
  <%= bootstrap_form_for @unit do |f| %>
    <%= f.text_area :name,
                    rows: 1,
                    minlength: 3,
                    maxlength: 30,
                    placeholder: 'Give your unit a name!',
                    class: 'form-control' %>

    <%= f.select(:calendar_id, @list) %>
    <%= f.text_field :address, value: @address %>
    <%= f.text_field :city, value: @city %>
    <%= f.select(:state, options_for_select(us_states, "GA"), value: @state) %>
    <%= f.text_field :zip_code, value: @zip_code %>


    <%= f.hidden_field :owner_id, value: current_user.id %>

    <%= f.submit "Create Unit!", id:'client-btn', class: 'form-control btn btn-primary'  %>
  <% end %>
  <%= link_to 'Back', units_path %>

</div>

app/views/units/show.html.erb
<div class='container' style='text-align:center'>
<p id="notice"><%= notice %></p>
<p id='unit-name'><%= "#{@unit.name}" %>
<% if current_user.id == @unit.owner.id %>
<%= link_to 'Edit', edit_unit_path(@unit) %> <% end %> |
<%= link_to 'Back', units_path %><br>
<p id='unit-address'><%= "#{@unit.address}, #{@unit.city}, #{@unit.state}, #{@unit.zip_code}" %></p>
<br><br>

<%= render 'units/map/map' %><br><br>

<div class="row">
  <%= render 'units/calendar/unit_calendar' %>
</div>

</div>