config/routes.rb
Rails.application.routes.draw do
  resources :units
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#index'
  get 'homepage', to: 'pages#homepage', as: 'homepage'
  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'user_details', to: 'pages#user_details', as: 'user_details'
  get 'calendar_legend', to:'pages#calendar_legend', as: 'calendar_legend'
  get 'how_to', to:'pages#how_to', as:'how_to'

  get '/redirect', to: 'events#redirect', as: 'redirect'
  get '/callback', to: 'events#callback', as: 'callback'
  get '/calendar', to: 'events#calendar', as: 'calendar'
  get '/events/:calendar_id', to: 'events#events', as: 'events', calendar_id: /[^\/]+/


  resources :bookings
  get 'booking_table', to:'bookings#booking_table', as:'booking_table'
  get 'request_message', to:'bookings#request_message', as:'request_message'
  post 'create_booking', to: 'bookings#create', as:'create_booking'
  put 'approve_booking/:id', to:'bookings#approve', as:'approve_booking'
  put 'deny_booking/:id', to:'bookings#deny', as:'deny_booking'
  put 'cancel_booking/:id', to:'bookings#cancel', as:'cancel_booking'
  post '/events/:calendar_id', to: 'bookings#new_event', as: 'new_event', calendar_id: /[^\/]+/
  # post 'destroy_bookings_and_events', to:'bookings#destroy_bookings_and_events', as: 'destroy_bookings_and_events'

  post 'delete_calendar', to:'units#delete_calendar', as:'delete_calendar'

  post 'twilio/sms'


  get 'bio', to:'users#bio', as:'bio'
  get 'user_table', to: 'users#index', as: 'user_table'


  #Devise routes for logging in, registrations
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy', as:'get_destroy_user_session'
  end




end

app/views/layouts/navigation/_collapsible_elements.html.erb
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse navbar-right" id="navbar-collapsible-content">
  <ul class="nav navbar-nav ">

    <% if user_signed_in? %>
      <li class="dropdown pc-menu">
        <a id="user-settings" class="dropdown-toggle" data-toggle="dropdown" href="#">
          <span id="user-name"><%= current_user.name %></span>
          <span class="caret"></span>
        </a>

        <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'Dashboard', dashboard_path %></li>
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>

      <li class="mobile-menu">
        <%= link_to 'Edit Profile', edit_user_registration_path %>
      </li>
      <li class="mobile-menu">
        <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
      </li>

    <% else # user not signed it %>
      <li ><%= link_to 'Login', login_path %></li>
      <li ><%= link_to 'Signup', signup_path %></li>
    <% end # if user is signed it %>
  </ul>
</div><!-- navbar-collapse -->

app/views/layouts/navigation/_header.html.erb
<div class="navbar-header">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapsible-content" aria-expanded="false">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <%= link_to 'CleanHost', root_path, class: 'navbar-brand' %>
</div>